<?php

// Data functions (insert, update, delete, form) for table address

// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

function address_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('address');
	if(!$arrPerm[1]){
		return false;
	}

	$data['address1'] = makeSafe($_REQUEST['address1']);
		if($data['address1'] == empty_lookup_value){ $data['address1'] = ''; }
	$data['address2'] = makeSafe($_REQUEST['address2']);
		if($data['address2'] == empty_lookup_value){ $data['address2'] = ''; }
	$data['address3'] = makeSafe($_REQUEST['address3']);
		if($data['address3'] == empty_lookup_value){ $data['address3'] = ''; }
	$data['town'] = makeSafe($_REQUEST['town']);
		if($data['town'] == empty_lookup_value){ $data['town'] = ''; }
	$data['county'] = makeSafe($_REQUEST['county']);
		if($data['county'] == empty_lookup_value){ $data['county'] = ''; }
	$data['country'] = makeSafe($_REQUEST['country']);
		if($data['country'] == empty_lookup_value){ $data['country'] = ''; }
	$data['postcode1'] = makeSafe($_REQUEST['postcode1']);
		if($data['postcode1'] == empty_lookup_value){ $data['postcode1'] = ''; }
	$data['postcode2'] = makeSafe($_REQUEST['postcode2']);
		if($data['postcode2'] == empty_lookup_value){ $data['postcode2'] = ''; }

	// hook: address_before_insert
	if(function_exists('address_before_insert')){
		$args=array();
		if(!address_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `address` set       `address1`=' . (($data['address1'] !== '' && $data['address1'] !== NULL) ? "'{$data['address1']}'" : 'NULL') . ', `address2`=' . (($data['address2'] !== '' && $data['address2'] !== NULL) ? "'{$data['address2']}'" : 'NULL') . ', `address3`=' . (($data['address3'] !== '' && $data['address3'] !== NULL) ? "'{$data['address3']}'" : 'NULL') . ', `town`=' . (($data['town'] !== '' && $data['town'] !== NULL) ? "'{$data['town']}'" : 'NULL') . ', `county`=' . (($data['county'] !== '' && $data['county'] !== NULL) ? "'{$data['county']}'" : 'NULL') . ', `country`=' . (($data['country'] !== '' && $data['country'] !== NULL) ? "'{$data['country']}'" : 'NULL') . ', `postcode1`=' . (($data['postcode1'] !== '' && $data['postcode1'] !== NULL) ? "'{$data['postcode1']}'" : 'NULL') . ', `postcode2`=' . (($data['postcode2'] !== '' && $data['postcode2'] !== NULL) ? "'{$data['postcode2']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"address_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: address_after_insert
	if(function_exists('address_after_insert')){
		$res = sql("select * from `address` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!address_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='address', pkValue='" . makeSafe($recID, false) . "', memberID='" . makeSafe(getLoggedMemberID(), false) . "', dateAdded='" . time() . "', dateUpdated='" . time() . "', groupID='" . getLoggedGroupID() . "'", $eo);

	return $recID;
}

function address_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('address');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='address' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='address' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: address_before_delete
	if(function_exists('address_before_delete')){
		$args=array();
		if(!address_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: property
	$res = sql("select `id` from `address` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `property` where `address_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "property", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "property", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='address_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='address_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: partner
	$res = sql("select `id` from `address` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `partner` where `address_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "partner", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "partner", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='address_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='address_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: loan
	$res = sql("select `id` from `address` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `loan` where `property_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "loan", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "loan", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='address_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='address_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `address` where `id`='$selected_id'", $eo);

	// hook: address_after_delete
	if(function_exists('address_after_delete')){
		$args=array();
		address_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='address' and pkValue='$selected_id'", $eo);
}

function address_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('address');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='address' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='address' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['address1'] = makeSafe($_REQUEST['address1']);
		if($data['address1'] == empty_lookup_value){ $data['address1'] = ''; }
	$data['address2'] = makeSafe($_REQUEST['address2']);
		if($data['address2'] == empty_lookup_value){ $data['address2'] = ''; }
	$data['address3'] = makeSafe($_REQUEST['address3']);
		if($data['address3'] == empty_lookup_value){ $data['address3'] = ''; }
	$data['town'] = makeSafe($_REQUEST['town']);
		if($data['town'] == empty_lookup_value){ $data['town'] = ''; }
	$data['county'] = makeSafe($_REQUEST['county']);
		if($data['county'] == empty_lookup_value){ $data['county'] = ''; }
	$data['country'] = makeSafe($_REQUEST['country']);
		if($data['country'] == empty_lookup_value){ $data['country'] = ''; }
	$data['postcode1'] = makeSafe($_REQUEST['postcode1']);
		if($data['postcode1'] == empty_lookup_value){ $data['postcode1'] = ''; }
	$data['postcode2'] = makeSafe($_REQUEST['postcode2']);
		if($data['postcode2'] == empty_lookup_value){ $data['postcode2'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: address_before_update
	if(function_exists('address_before_update')){
		$args=array();
		if(!address_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `address` set       `address1`=' . (($data['address1'] !== '' && $data['address1'] !== NULL) ? "'{$data['address1']}'" : 'NULL') . ', `address2`=' . (($data['address2'] !== '' && $data['address2'] !== NULL) ? "'{$data['address2']}'" : 'NULL') . ', `address3`=' . (($data['address3'] !== '' && $data['address3'] !== NULL) ? "'{$data['address3']}'" : 'NULL') . ', `town`=' . (($data['town'] !== '' && $data['town'] !== NULL) ? "'{$data['town']}'" : 'NULL') . ', `county`=' . (($data['county'] !== '' && $data['county'] !== NULL) ? "'{$data['county']}'" : 'NULL') . ', `country`=' . (($data['country'] !== '' && $data['country'] !== NULL) ? "'{$data['country']}'" : 'NULL') . ', `postcode1`=' . (($data['postcode1'] !== '' && $data['postcode1'] !== NULL) ? "'{$data['postcode1']}'" : 'NULL') . ', `postcode2`=' . (($data['postcode2'] !== '' && $data['postcode2'] !== NULL) ? "'{$data['postcode2']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="address_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: address_after_update
	if(function_exists('address_after_update')){
		$res = sql("SELECT * FROM `address` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!address_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='address' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function address_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('address');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_county = thisOr(undo_magic_quotes($_REQUEST['filterer_county']), '');
	$filterer_country = thisOr(undo_magic_quotes($_REQUEST['filterer_country']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: county
	$combo_county = new DataCombo;
	// combobox: country
	$combo_country = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='address' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='address' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `address` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'address_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_county->SelectedData = $row['county'];
		$combo_country->SelectedData = $row['country'];
	}else{
		$combo_county->SelectedData = $filterer_county;
		$combo_country->SelectedData = $filterer_country;
	}
	$combo_county->HTML = '<span id="county-container' . $rnd1 . '"></span><input type="hidden" name="county" id="county' . $rnd1 . '" value="' . html_attr($combo_county->SelectedData) . '">';
	$combo_county->MatchText = '<span id="county-container-readonly' . $rnd1 . '"></span><input type="hidden" name="county" id="county' . $rnd1 . '" value="' . html_attr($combo_county->SelectedData) . '">';
	$combo_country->HTML = '<span id="country-container' . $rnd1 . '"></span><input type="hidden" name="country" id="country' . $rnd1 . '" value="' . html_attr($combo_country->SelectedData) . '">';
	$combo_country->MatchText = '<span id="country-container-readonly' . $rnd1 . '"></span><input type="hidden" name="country" id="country' . $rnd1 . '" value="' . html_attr($combo_country->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_county__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['county'] : $filterer_county); ?>"};
		AppGini.current_country__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['country'] : $filterer_country); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(county_reload__RAND__) == 'function') county_reload__RAND__();
				if(typeof(country_reload__RAND__) == 'function') country_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function county_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#county-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_county__RAND__.value, t: 'address', f: 'county' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="county"]').val(resp.results[0].id);
							$j('[id=county-container-readonly__RAND__]').html('<span id="county-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=county_view_parent]').hide(); }else{ $j('.btn[id=county_view_parent]').show(); }


							if(typeof(county_update_autofills__RAND__) == 'function') county_update_autofills__RAND__();
						}
					});
				},
				width: ($j('fieldset .col-xs-11').width() - select2_max_width_decrement()) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'address', f: 'county' }; },
					results: function(resp, page){ return resp; }
				},
				escapeMarkup: function(str){ return str; }
			}).on('change', function(e){
				AppGini.current_county__RAND__.value = e.added.id;
				AppGini.current_county__RAND__.text = e.added.text;
				$j('[name="county"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=county_view_parent]').hide(); }else{ $j('.btn[id=county_view_parent]').show(); }


				if(typeof(county_update_autofills__RAND__) == 'function') county_update_autofills__RAND__();
			});

			if(!$j("#county-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_county__RAND__.value, t: 'address', f: 'county' },
					success: function(resp){
						$j('[name="county"]').val(resp.results[0].id);
						$j('[id=county-container-readonly__RAND__]').html('<span id="county-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=county_view_parent]').hide(); }else{ $j('.btn[id=county_view_parent]').show(); }

						if(typeof(county_update_autofills__RAND__) == 'function') county_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_county__RAND__.value, t: 'address', f: 'county' },
				success: function(resp){
					$j('[id=county-container__RAND__], [id=county-container-readonly__RAND__]').html('<span id="county-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=county_view_parent]').hide(); }else{ $j('.btn[id=county_view_parent]').show(); }

					if(typeof(county_update_autofills__RAND__) == 'function') county_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function country_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#country-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_country__RAND__.value, t: 'address', f: 'country' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="country"]').val(resp.results[0].id);
							$j('[id=country-container-readonly__RAND__]').html('<span id="country-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=country_view_parent]').hide(); }else{ $j('.btn[id=country_view_parent]').show(); }


							if(typeof(country_update_autofills__RAND__) == 'function') country_update_autofills__RAND__();
						}
					});
				},
				width: ($j('fieldset .col-xs-11').width() - select2_max_width_decrement()) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'address', f: 'country' }; },
					results: function(resp, page){ return resp; }
				},
				escapeMarkup: function(str){ return str; }
			}).on('change', function(e){
				AppGini.current_country__RAND__.value = e.added.id;
				AppGini.current_country__RAND__.text = e.added.text;
				$j('[name="country"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=country_view_parent]').hide(); }else{ $j('.btn[id=country_view_parent]').show(); }


				if(typeof(country_update_autofills__RAND__) == 'function') country_update_autofills__RAND__();
			});

			if(!$j("#country-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_country__RAND__.value, t: 'address', f: 'country' },
					success: function(resp){
						$j('[name="country"]').val(resp.results[0].id);
						$j('[id=country-container-readonly__RAND__]').html('<span id="country-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=country_view_parent]').hide(); }else{ $j('.btn[id=country_view_parent]').show(); }

						if(typeof(country_update_autofills__RAND__) == 'function') country_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_country__RAND__.value, t: 'address', f: 'country' },
				success: function(resp){
					$j('[id=country-container__RAND__], [id=country-container-readonly__RAND__]').html('<span id="country-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=country_view_parent]').hide(); }else{ $j('.btn[id=country_view_parent]').show(); }

					if(typeof(country_update_autofills__RAND__) == 'function') country_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/address_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/address_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Addres details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return address_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return address_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return address_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#address1').replaceWith('<div class=\"form-control-static\" id=\"address1\">' + (jQuery('#address1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#address2').replaceWith('<div class=\"form-control-static\" id=\"address2\">' + (jQuery('#address2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#address3').replaceWith('<div class=\"form-control-static\" id=\"address3\">' + (jQuery('#address3').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#town').replaceWith('<div class=\"form-control-static\" id=\"town\">' + (jQuery('#town').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#county').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#county_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#country').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#country_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#postcode1').replaceWith('<div class=\"form-control-static\" id=\"postcode1\">' + (jQuery('#postcode1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#postcode2').replaceWith('<div class=\"form-control-static\" id=\"postcode2\">' + (jQuery('#postcode2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(county)%%>', $combo_county->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(county)%%>', $combo_county->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(county)%%>', urlencode($combo_county->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(country)%%>', $combo_country->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(country)%%>', $combo_country->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(country)%%>', urlencode($combo_country->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'county' => array('county', 'County'), 'country' => array('country', 'Country'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(address1)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(address2)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(address3)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(town)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(county)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(country)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(postcode1)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(postcode2)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(address1)%%>', html_attr($row['address1']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(address1)%%>', urlencode($urow['address1']), $templateCode);
		$templateCode=str_replace('<%%VALUE(address2)%%>', html_attr($row['address2']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(address2)%%>', urlencode($urow['address2']), $templateCode);
		$templateCode=str_replace('<%%VALUE(address3)%%>', html_attr($row['address3']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(address3)%%>', urlencode($urow['address3']), $templateCode);
		$templateCode=str_replace('<%%VALUE(town)%%>', html_attr($row['town']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(town)%%>', urlencode($urow['town']), $templateCode);
		$templateCode=str_replace('<%%VALUE(county)%%>', html_attr($row['county']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(county)%%>', urlencode($urow['county']), $templateCode);
		$templateCode=str_replace('<%%VALUE(country)%%>', html_attr($row['country']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(country)%%>', urlencode($urow['country']), $templateCode);
		$templateCode=str_replace('<%%VALUE(postcode1)%%>', html_attr($row['postcode1']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(postcode1)%%>', urlencode($urow['postcode1']), $templateCode);
		$templateCode=str_replace('<%%VALUE(postcode2)%%>', html_attr($row['postcode2']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(postcode2)%%>', urlencode($urow['postcode2']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(address1)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(address1)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(address2)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(address2)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(address3)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(address3)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(town)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(town)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(county)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(county)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(country)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(country)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(postcode1)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(postcode1)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(postcode2)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(postcode2)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('address');
	if($selected_id){
		$jdata = get_joined_record('address', $selected_id);
		$rdata = $row;
	}
	$cache_data = array(
		'rdata' => array_map('nl2br', array_map('addslashes', $rdata)),
		'jdata' => array_map('nl2br', array_map('addslashes', $jdata)),
	);
	$templateCode .= loadView('address-ajax-cache', $cache_data);

	// hook: address_dv
	if(function_exists('address_dv')){
		$args=array();
		address_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>