<?php
// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/leads.php");
	include("$currDir/leads_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('leads');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "leads";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`leads`.`id`" => "id",
		"`leads`.`name`" => "name",
		"`leads`.`email`" => "email",
		"`leads`.`phone`" => "phone",
		"`leads`.`prop_area`" => "prop_area",
		"`leads`.`tenanted`" => "tenanted",
		"`leads`.`notes`" => "notes",
		"if(`leads`.`date_entered`,date_format(`leads`.`date_entered`,'%d/%m/%Y'),'')" => "date_entered",
		"if(`leads`.`date_contacted`,date_format(`leads`.`date_contacted`,'%d/%m/%Y'),'')" => "date_contacted",
		"`leads`.`est_value`" => "est_value",
		"`leads`.`os_capital`" => "os_capital",
		"`leads`.`rental_income`" => "rental_income",
		"`leads`.`finance_costs`" => "finance_costs",
		"`leads`.`other_costs`" => "other_costs",
		"`leads`.`income_tax_band`" => "income_tax_band",
		"`leads`.`referer`" => "referer",
		"`leads`.`est_commission`" => "est_commission"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`leads`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => '`leads`.`date_entered`',
		9 => '`leads`.`date_contacted`',
		10 => 10,
		11 => 11,
		12 => '`leads`.`rental_income`',
		13 => '`leads`.`finance_costs`',
		14 => '`leads`.`other_costs`',
		15 => 15,
		16 => 16,
		17 => '`leads`.`est_commission`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`leads`.`id`" => "id",
		"`leads`.`name`" => "name",
		"`leads`.`email`" => "email",
		"`leads`.`phone`" => "phone",
		"`leads`.`prop_area`" => "prop_area",
		"`leads`.`tenanted`" => "tenanted",
		"`leads`.`notes`" => "notes",
		"if(`leads`.`date_entered`,date_format(`leads`.`date_entered`,'%d/%m/%Y'),'')" => "date_entered",
		"if(`leads`.`date_contacted`,date_format(`leads`.`date_contacted`,'%d/%m/%Y'),'')" => "date_contacted",
		"`leads`.`est_value`" => "est_value",
		"`leads`.`os_capital`" => "os_capital",
		"`leads`.`rental_income`" => "rental_income",
		"`leads`.`finance_costs`" => "finance_costs",
		"`leads`.`other_costs`" => "other_costs",
		"`leads`.`income_tax_band`" => "income_tax_band",
		"`leads`.`referer`" => "referer",
		"`leads`.`est_commission`" => "est_commission"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`leads`.`id`" => "ID",
		"`leads`.`name`" => "Name",
		"`leads`.`email`" => "Email",
		"`leads`.`phone`" => "Phone",
		"`leads`.`prop_area`" => "Property area",
		"`leads`.`tenanted`" => "Tenanted",
		"`leads`.`notes`" => "Notes",
		"`leads`.`date_entered`" => "Date entered",
		"`leads`.`date_contacted`" => "Date contacted",
		"`leads`.`est_value`" => "Est. market value",
		"`leads`.`os_capital`" => "O/S capital",
		"`leads`.`rental_income`" => "Rental income",
		"`leads`.`finance_costs`" => "Finance costs",
		"`leads`.`other_costs`" => "Other costs",
		"`leads`.`income_tax_band`" => "Income tax band",
		"`leads`.`referer`" => "Referer",
		"`leads`.`est_commission`" => "Est commission"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`leads`.`id`" => "id",
		"`leads`.`name`" => "name",
		"`leads`.`email`" => "email",
		"`leads`.`phone`" => "phone",
		"`leads`.`prop_area`" => "prop_area",
		"`leads`.`tenanted`" => "tenanted",
		"`leads`.`notes`" => "notes",
		"if(`leads`.`date_entered`,date_format(`leads`.`date_entered`,'%d/%m/%Y'),'')" => "date_entered",
		"if(`leads`.`date_contacted`,date_format(`leads`.`date_contacted`,'%d/%m/%Y'),'')" => "date_contacted",
		"`leads`.`est_value`" => "est_value",
		"`leads`.`os_capital`" => "os_capital",
		"`leads`.`rental_income`" => "rental_income",
		"`leads`.`finance_costs`" => "finance_costs",
		"`leads`.`other_costs`" => "other_costs",
		"`leads`.`income_tax_band`" => "income_tax_band",
		"`leads`.`referer`" => "referer",
		"`leads`.`est_commission`" => "est_commission"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`leads` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "leads_view.php";
	$x->RedirectAfterInsert = "leads_view.php?SelectedID=#ID#";
	$x->TableTitle = "Leads";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`leads`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Name", "Email", "Phone", "Property area", "Tenanted", "Notes", "Est. market value", "O/S capital", "Rental income", "Finance costs", "Other costs", "Income tax band");
	$x->ColFieldName = array('name', 'email', 'phone', 'prop_area', 'tenanted', 'notes', 'est_value', 'os_capital', 'rental_income', 'finance_costs', 'other_costs', 'income_tax_band');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15);

	// template paths below are based on the app main directory
	$x->Template = 'templates/leads_templateTV.html';
	$x->SelectedTemplate = 'templates/leads_templateTVS.html';
	$x->TemplateDV = 'templates/leads_templateDV.html';
	$x->TemplateDVP = 'templates/leads_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `leads`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='leads' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `leads`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='leads' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`leads`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: leads_init
	$render=TRUE;
	if(function_exists('leads_init')){
		$args=array();
		$render=leads_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: leads_header
	$headerCode='';
	if(function_exists('leads_header')){
		$args=array();
		$headerCode=leads_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: leads_footer
	$footerCode='';
	if(function_exists('leads_footer')){
		$args=array();
		$footerCode=leads_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>