<?php
// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/leads.php");
	include("$currDir/leads_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('leads');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "leads";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`leads`.`id`" => "id",
		"`leads`.`date_entered`" => "date_entered",
		"`leads`.`referer`" => "referer",
		"`leads`.`lead_name`" => "lead_name",
		"`leads`.`contact`" => "contact",
		"`leads`.`prop_area`" => "prop_area",
		"`leads`.`estimated_value`" => "estimated_value",
		"`leads`.`tenanted`" => "tenanted",
		"`leads`.`rental_income`" => "rental_income",
		"`leads`.`notes`" => "notes",
		"`leads`.`est_commission`" => "est_commission",
		"if(`leads`.`date_contacted`,date_format(`leads`.`date_contacted`,'%d/%m/%Y'),'')" => "date_contacted"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`leads`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`leads`.`estimated_value`',
		8 => 8,
		9 => 9,
		10 => 10,
		11 => '`leads`.`est_commission`',
		12 => '`leads`.`date_contacted`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`leads`.`id`" => "id",
		"`leads`.`date_entered`" => "date_entered",
		"`leads`.`referer`" => "referer",
		"`leads`.`lead_name`" => "lead_name",
		"`leads`.`contact`" => "contact",
		"`leads`.`prop_area`" => "prop_area",
		"`leads`.`estimated_value`" => "estimated_value",
		"`leads`.`tenanted`" => "tenanted",
		"`leads`.`rental_income`" => "rental_income",
		"`leads`.`notes`" => "notes",
		"`leads`.`est_commission`" => "est_commission",
		"if(`leads`.`date_contacted`,date_format(`leads`.`date_contacted`,'%d/%m/%Y'),'')" => "date_contacted"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`leads`.`id`" => "Reference",
		"`leads`.`date_entered`" => "Date entered",
		"`leads`.`referer`" => "Referral source",
		"`leads`.`lead_name`" => "Client Name",
		"`leads`.`contact`" => "Contact details",
		"`leads`.`prop_area`" => "First part postcode",
		"`leads`.`estimated_value`" => "Estimated value",
		"`leads`.`tenanted`" => "Tenanted",
		"`leads`.`rental_income`" => "Monthly Rental income",
		"`leads`.`notes`" => "Notes",
		"`leads`.`est_commission`" => "Estimated Commission",
		"`leads`.`date_contacted`" => "Date contacted"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`leads`.`id`" => "id",
		"`leads`.`date_entered`" => "date_entered",
		"`leads`.`referer`" => "referer",
		"`leads`.`lead_name`" => "lead_name",
		"`leads`.`contact`" => "contact",
		"`leads`.`prop_area`" => "prop_area",
		"`leads`.`estimated_value`" => "estimated_value",
		"`leads`.`tenanted`" => "tenanted",
		"`leads`.`rental_income`" => "rental_income",
		"`leads`.`notes`" => "notes",
		"`leads`.`est_commission`" => "est_commission",
		"if(`leads`.`date_contacted`,date_format(`leads`.`date_contacted`,'%d/%m/%Y'),'')" => "date_contacted"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`leads` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 0;
	$x->AllowCSV = 0;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "leads_view.php";
	$x->RedirectAfterInsert = "leads_view.php?SelectedID=#ID#";
	$x->TableTitle = "Leads";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`leads`.`id`";
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Date entered", "Referral source", "Client Name", "Contact details", "First part postcode", "Estimated value", "Tenanted", "Monthly Rental income", "Notes", "Estimated Commission", "Date contacted");
	$x->ColFieldName = array('date_entered', 'referer', 'lead_name', 'contact', 'prop_area', 'estimated_value', 'tenanted', 'rental_income', 'notes', 'est_commission', 'date_contacted');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12);

	// template paths below are based on the app main directory
	$x->Template = 'templates/leads_templateTV.html';
	$x->SelectedTemplate = 'templates/leads_templateTVS.html';
	$x->TemplateDV = 'templates/leads_templateDV.html';
	$x->TemplateDVP = 'templates/leads_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `leads`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='leads' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `leads`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='leads' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`leads`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: leads_init
	$render=TRUE;
	if(function_exists('leads_init')){
		$args=array();
		$render=leads_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: leads_header
	$headerCode='';
	if(function_exists('leads_header')){
		$args=array();
		$headerCode=leads_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: leads_footer
	$footerCode='';
	if(function_exists('leads_footer')){
		$args=array();
		$footerCode=leads_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>