<?php
// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/loan.php");
	include("$currDir/loan_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('loan');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "loan";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`loan`.`id`" => "id",
		"IF(    CHAR_LENGTH(`loan_type1`.`type`), CONCAT_WS('',   `loan_type1`.`type`), '') /* Loan type */" => "loan_type",
		"IF(    CHAR_LENGTH(`address1`.`postcode1`) || CHAR_LENGTH(`address1`.`address1`), CONCAT_WS('',   `address1`.`postcode1`, ' - ', `address1`.`address1`), '') /* Property id */" => "property_id",
		"IF(    CHAR_LENGTH(`client1`.`company_name`), CONCAT_WS('',   `client1`.`company_name`), '') /* Broker id */" => "broker_id",
		"if(`loan`.`date`,date_format(`loan`.`date`,'%d/%m/%Y'),'')" => "date",
		"`loan`.`amount`" => "amount",
		"`loan`.`costs`" => "costs",
		"`loan`.`apr`" => "apr",
		"`loan`.`outstanding`" => "outstanding",
		"IF(    CHAR_LENGTH(`client2`.`company_name`), CONCAT_WS('',   `client2`.`company_name`), '') /* Lender id */" => "lender_id",
		"`loan`.`lender_ref`" => "lender_ref"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`loan`.`id`',
		2 => '`loan_type1`.`type`',
		3 => 3,
		4 => '`client1`.`company_name`',
		5 => '`loan`.`date`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => '`client2`.`company_name`',
		11 => 11
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`loan`.`id`" => "id",
		"IF(    CHAR_LENGTH(`loan_type1`.`type`), CONCAT_WS('',   `loan_type1`.`type`), '') /* Loan type */" => "loan_type",
		"IF(    CHAR_LENGTH(`address1`.`postcode1`) || CHAR_LENGTH(`address1`.`address1`), CONCAT_WS('',   `address1`.`postcode1`, ' - ', `address1`.`address1`), '') /* Property id */" => "property_id",
		"IF(    CHAR_LENGTH(`client1`.`company_name`), CONCAT_WS('',   `client1`.`company_name`), '') /* Broker id */" => "broker_id",
		"if(`loan`.`date`,date_format(`loan`.`date`,'%d/%m/%Y'),'')" => "date",
		"`loan`.`amount`" => "amount",
		"`loan`.`costs`" => "costs",
		"`loan`.`apr`" => "apr",
		"`loan`.`outstanding`" => "outstanding",
		"IF(    CHAR_LENGTH(`client2`.`company_name`), CONCAT_WS('',   `client2`.`company_name`), '') /* Lender id */" => "lender_id",
		"`loan`.`lender_ref`" => "lender_ref"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`loan`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`loan_type1`.`type`), CONCAT_WS('',   `loan_type1`.`type`), '') /* Loan type */" => "Loan type",
		"IF(    CHAR_LENGTH(`address1`.`postcode1`) || CHAR_LENGTH(`address1`.`address1`), CONCAT_WS('',   `address1`.`postcode1`, ' - ', `address1`.`address1`), '') /* Property id */" => "Property id",
		"IF(    CHAR_LENGTH(`client1`.`company_name`), CONCAT_WS('',   `client1`.`company_name`), '') /* Broker id */" => "Broker id",
		"`loan`.`date`" => "Date",
		"`loan`.`amount`" => "Amount",
		"`loan`.`costs`" => "Costs",
		"`loan`.`apr`" => "Apr",
		"`loan`.`outstanding`" => "Outstanding",
		"IF(    CHAR_LENGTH(`client2`.`company_name`), CONCAT_WS('',   `client2`.`company_name`), '') /* Lender id */" => "Lender id",
		"`loan`.`lender_ref`" => "Lender ref"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`loan`.`id`" => "id",
		"IF(    CHAR_LENGTH(`loan_type1`.`type`), CONCAT_WS('',   `loan_type1`.`type`), '') /* Loan type */" => "loan_type",
		"IF(    CHAR_LENGTH(`address1`.`postcode1`) || CHAR_LENGTH(`address1`.`address1`), CONCAT_WS('',   `address1`.`postcode1`, ' - ', `address1`.`address1`), '') /* Property id */" => "property_id",
		"IF(    CHAR_LENGTH(`client1`.`company_name`), CONCAT_WS('',   `client1`.`company_name`), '') /* Broker id */" => "broker_id",
		"if(`loan`.`date`,date_format(`loan`.`date`,'%d/%m/%Y'),'')" => "date",
		"`loan`.`amount`" => "amount",
		"`loan`.`costs`" => "costs",
		"`loan`.`apr`" => "apr",
		"`loan`.`outstanding`" => "outstanding",
		"IF(    CHAR_LENGTH(`client2`.`company_name`), CONCAT_WS('',   `client2`.`company_name`), '') /* Lender id */" => "lender_id",
		"`loan`.`lender_ref`" => "lender_ref"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'loan_type' => 'Loan type', 'property_id' => 'Property id', 'broker_id' => 'Broker id', 'lender_id' => 'Lender id');

	$x->QueryFrom = "`loan` LEFT JOIN `loan_type` as loan_type1 ON `loan_type1`.`id`=`loan`.`loan_type` LEFT JOIN `address` as address1 ON `address1`.`id`=`loan`.`property_id` LEFT JOIN `client` as client1 ON `client1`.`id`=`loan`.`broker_id` LEFT JOIN `client` as client2 ON `client2`.`id`=`loan`.`lender_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "loan_view.php";
	$x->RedirectAfterInsert = "loan_view.php?SelectedID=#ID#";
	$x->TableTitle = "Loan";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`loan`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Loan type", "Property id", "Broker id", "Date", "Amount", "Costs", "Apr", "Outstanding", "Lender id", "Lender ref");
	$x->ColFieldName = array('loan_type', 'property_id', 'broker_id', 'date', 'amount', 'costs', 'apr', 'outstanding', 'lender_id', 'lender_ref');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11);

	// template paths below are based on the app main directory
	$x->Template = 'templates/loan_templateTV.html';
	$x->SelectedTemplate = 'templates/loan_templateTVS.html';
	$x->TemplateDV = 'templates/loan_templateDV.html';
	$x->TemplateDVP = 'templates/loan_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `loan`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='loan' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `loan`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='loan' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`loan`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: loan_init
	$render=TRUE;
	if(function_exists('loan_init')){
		$args=array();
		$render=loan_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: loan_header
	$headerCode='';
	if(function_exists('loan_header')){
		$args=array();
		$headerCode=loan_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: loan_footer
	$footerCode='';
	if(function_exists('loan_footer')){
		$args=array();
		$footerCode=loan_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>