<?php

// Data functions (insert, update, delete, form) for table partner

// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

function partner_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('partner');
	if(!$arrPerm[1]){
		return false;
	}

	$data['company_name'] = makeSafe($_REQUEST['company_name']);
		if($data['company_name'] == empty_lookup_value){ $data['company_name'] = ''; }
	$data['title'] = makeSafe($_REQUEST['title']);
		if($data['title'] == empty_lookup_value){ $data['title'] = ''; }
	$data['fname'] = makeSafe($_REQUEST['fname']);
		if($data['fname'] == empty_lookup_value){ $data['fname'] = ''; }
	$data['lname'] = makeSafe($_REQUEST['lname']);
		if($data['lname'] == empty_lookup_value){ $data['lname'] = ''; }
	$data['mailname'] = makeSafe($_REQUEST['mailname']);
		if($data['mailname'] == empty_lookup_value){ $data['mailname'] = ''; }
	$data['email'] = br2nl(makeSafe($_REQUEST['email']));
	$data['phone'] = makeSafe($_REQUEST['phone']);
		if($data['phone'] == empty_lookup_value){ $data['phone'] = ''; }
	$data['mobile'] = makeSafe($_REQUEST['mobile']);
		if($data['mobile'] == empty_lookup_value){ $data['mobile'] = ''; }
	$data['address_id'] = makeSafe($_REQUEST['address_id']);
		if($data['address_id'] == empty_lookup_value){ $data['address_id'] = ''; }
	$data['username'] = makeSafe($_REQUEST['username']);
		if($data['username'] == empty_lookup_value){ $data['username'] = ''; }
	$data['password'] = makeSafe($_REQUEST['password']);
		if($data['password'] == empty_lookup_value){ $data['password'] = ''; }
	$data['type1'] = makeSafe($_REQUEST['type1']);
		if($data['type1'] == empty_lookup_value){ $data['type1'] = ''; }
	$data['type2'] = makeSafe($_REQUEST['type2']);
		if($data['type2'] == empty_lookup_value){ $data['type2'] = ''; }
	$data['type3'] = makeSafe($_REQUEST['type3']);
		if($data['type3'] == empty_lookup_value){ $data['type3'] = ''; }
	$data['commission_rate'] = makeSafe($_REQUEST['commission_rate']);
		if($data['commission_rate'] == empty_lookup_value){ $data['commission_rate'] = ''; }
	if($data['commission_rate'] == '') $data['commission_rate'] = "0.50";

	// hook: partner_before_insert
	if(function_exists('partner_before_insert')){
		$args=array();
		if(!partner_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `partner` set       `company_name`=' . (($data['company_name'] !== '' && $data['company_name'] !== NULL) ? "'{$data['company_name']}'" : 'NULL') . ', `title`=' . (($data['title'] !== '' && $data['title'] !== NULL) ? "'{$data['title']}'" : 'NULL') . ', `fname`=' . (($data['fname'] !== '' && $data['fname'] !== NULL) ? "'{$data['fname']}'" : 'NULL') . ', `lname`=' . (($data['lname'] !== '' && $data['lname'] !== NULL) ? "'{$data['lname']}'" : 'NULL') . ', `mailname`=' . (($data['mailname'] !== '' && $data['mailname'] !== NULL) ? "'{$data['mailname']}'" : 'NULL') . ', `email`=' . (($data['email'] !== '' && $data['email'] !== NULL) ? "'{$data['email']}'" : 'NULL') . ', `phone`=' . (($data['phone'] !== '' && $data['phone'] !== NULL) ? "'{$data['phone']}'" : 'NULL') . ', `mobile`=' . (($data['mobile'] !== '' && $data['mobile'] !== NULL) ? "'{$data['mobile']}'" : 'NULL') . ', `address_id`=' . (($data['address_id'] !== '' && $data['address_id'] !== NULL) ? "'{$data['address_id']}'" : 'NULL') . ', `username`=' . (($data['username'] !== '' && $data['username'] !== NULL) ? "'{$data['username']}'" : 'NULL') . ', `password`=' . (($data['password'] !== '' && $data['password'] !== NULL) ? "'{$data['password']}'" : 'NULL') . ', `type1`=' . (($data['type1'] !== '' && $data['type1'] !== NULL) ? "'{$data['type1']}'" : 'NULL') . ', `type2`=' . (($data['type2'] !== '' && $data['type2'] !== NULL) ? "'{$data['type2']}'" : 'NULL') . ', `type3`=' . (($data['type3'] !== '' && $data['type3'] !== NULL) ? "'{$data['type3']}'" : 'NULL') . ', `commission_rate`=' . (($data['commission_rate'] !== '' && $data['commission_rate'] !== NULL) ? "'{$data['commission_rate']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"partner_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: partner_after_insert
	if(function_exists('partner_after_insert')){
		$res = sql("select * from `partner` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!partner_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='partner', pkValue='" . makeSafe($recID, false) . "', memberID='" . makeSafe(getLoggedMemberID(), false) . "', dateAdded='" . time() . "', dateUpdated='" . time() . "', groupID='" . getLoggedGroupID() . "'", $eo);

	return $recID;
}

function partner_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('partner');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='partner' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='partner' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: partner_before_delete
	if(function_exists('partner_before_delete')){
		$args=array();
		if(!partner_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: property
	$res = sql("select `id` from `partner` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `property` where `partner_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "property", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "property", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='partner_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='partner_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: property
	$res = sql("select `id` from `partner` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `property` where `referer`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "property", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "property", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='partner_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='partner_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: loan
	$res = sql("select `id` from `partner` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `loan` where `broker_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "loan", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "loan", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='partner_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='partner_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: loan
	$res = sql("select `id` from `partner` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `loan` where `lender_id`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "loan", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "loan", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='partner_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='partner_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `partner` where `id`='$selected_id'", $eo);

	// hook: partner_after_delete
	if(function_exists('partner_after_delete')){
		$args=array();
		partner_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='partner' and pkValue='$selected_id'", $eo);
}

function partner_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('partner');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='partner' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='partner' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['company_name'] = makeSafe($_REQUEST['company_name']);
		if($data['company_name'] == empty_lookup_value){ $data['company_name'] = ''; }
	$data['title'] = makeSafe($_REQUEST['title']);
		if($data['title'] == empty_lookup_value){ $data['title'] = ''; }
	$data['fname'] = makeSafe($_REQUEST['fname']);
		if($data['fname'] == empty_lookup_value){ $data['fname'] = ''; }
	$data['lname'] = makeSafe($_REQUEST['lname']);
		if($data['lname'] == empty_lookup_value){ $data['lname'] = ''; }
	$data['mailname'] = makeSafe($_REQUEST['mailname']);
		if($data['mailname'] == empty_lookup_value){ $data['mailname'] = ''; }
	$data['email'] = br2nl(makeSafe($_REQUEST['email']));
	$data['phone'] = makeSafe($_REQUEST['phone']);
		if($data['phone'] == empty_lookup_value){ $data['phone'] = ''; }
	$data['mobile'] = makeSafe($_REQUEST['mobile']);
		if($data['mobile'] == empty_lookup_value){ $data['mobile'] = ''; }
	$data['address_id'] = makeSafe($_REQUEST['address_id']);
		if($data['address_id'] == empty_lookup_value){ $data['address_id'] = ''; }
	$data['username'] = makeSafe($_REQUEST['username']);
		if($data['username'] == empty_lookup_value){ $data['username'] = ''; }
	$data['password'] = makeSafe($_REQUEST['password']);
		if($data['password'] == empty_lookup_value){ $data['password'] = ''; }
	$data['type1'] = makeSafe($_REQUEST['type1']);
		if($data['type1'] == empty_lookup_value){ $data['type1'] = ''; }
	$data['type2'] = makeSafe($_REQUEST['type2']);
		if($data['type2'] == empty_lookup_value){ $data['type2'] = ''; }
	$data['type3'] = makeSafe($_REQUEST['type3']);
		if($data['type3'] == empty_lookup_value){ $data['type3'] = ''; }
	$data['commission_rate'] = makeSafe($_REQUEST['commission_rate']);
		if($data['commission_rate'] == empty_lookup_value){ $data['commission_rate'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: partner_before_update
	if(function_exists('partner_before_update')){
		$args=array();
		if(!partner_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `partner` set       `company_name`=' . (($data['company_name'] !== '' && $data['company_name'] !== NULL) ? "'{$data['company_name']}'" : 'NULL') . ', `title`=' . (($data['title'] !== '' && $data['title'] !== NULL) ? "'{$data['title']}'" : 'NULL') . ', `fname`=' . (($data['fname'] !== '' && $data['fname'] !== NULL) ? "'{$data['fname']}'" : 'NULL') . ', `lname`=' . (($data['lname'] !== '' && $data['lname'] !== NULL) ? "'{$data['lname']}'" : 'NULL') . ', `mailname`=' . (($data['mailname'] !== '' && $data['mailname'] !== NULL) ? "'{$data['mailname']}'" : 'NULL') . ', `email`=' . (($data['email'] !== '' && $data['email'] !== NULL) ? "'{$data['email']}'" : 'NULL') . ', `phone`=' . (($data['phone'] !== '' && $data['phone'] !== NULL) ? "'{$data['phone']}'" : 'NULL') . ', `mobile`=' . (($data['mobile'] !== '' && $data['mobile'] !== NULL) ? "'{$data['mobile']}'" : 'NULL') . ', `address_id`=' . (($data['address_id'] !== '' && $data['address_id'] !== NULL) ? "'{$data['address_id']}'" : 'NULL') . ', `username`=' . (($data['username'] !== '' && $data['username'] !== NULL) ? "'{$data['username']}'" : 'NULL') . ', `password`=' . (($data['password'] !== '' && $data['password'] !== NULL) ? "'{$data['password']}'" : 'NULL') . ', `type1`=' . (($data['type1'] !== '' && $data['type1'] !== NULL) ? "'{$data['type1']}'" : 'NULL') . ', `type2`=' . (($data['type2'] !== '' && $data['type2'] !== NULL) ? "'{$data['type2']}'" : 'NULL') . ', `type3`=' . (($data['type3'] !== '' && $data['type3'] !== NULL) ? "'{$data['type3']}'" : 'NULL') . ', `commission_rate`=' . (($data['commission_rate'] !== '' && $data['commission_rate'] !== NULL) ? "'{$data['commission_rate']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="partner_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: partner_after_update
	if(function_exists('partner_after_update')){
		$res = sql("SELECT * FROM `partner` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!partner_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='partner' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function partner_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('partner');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_title = thisOr(undo_magic_quotes($_REQUEST['filterer_title']), '');
	$filterer_address_id = thisOr(undo_magic_quotes($_REQUEST['filterer_address_id']), '');
	$filterer_type1 = thisOr(undo_magic_quotes($_REQUEST['filterer_type1']), '');
	$filterer_type2 = thisOr(undo_magic_quotes($_REQUEST['filterer_type2']), '');
	$filterer_type3 = thisOr(undo_magic_quotes($_REQUEST['filterer_type3']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: title
	$combo_title = new DataCombo;
	// combobox: address_id
	$combo_address_id = new DataCombo;
	// combobox: type1
	$combo_type1 = new DataCombo;
	// combobox: type2
	$combo_type2 = new DataCombo;
	// combobox: type3
	$combo_type3 = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='partner' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='partner' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `partner` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'partner_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_title->SelectedData = $row['title'];
		$combo_address_id->SelectedData = $row['address_id'];
		$combo_type1->SelectedData = $row['type1'];
		$combo_type2->SelectedData = $row['type2'];
		$combo_type3->SelectedData = $row['type3'];
	}else{
		$combo_title->SelectedData = $filterer_title;
		$combo_address_id->SelectedData = $filterer_address_id;
		$combo_type1->SelectedData = $filterer_type1;
		$combo_type2->SelectedData = $filterer_type2;
		$combo_type3->SelectedData = $filterer_type3;
	}
	$combo_title->HTML = $combo_title->MatchText = '<span id="title-container' . $rnd1 . '"></span>';
	$combo_address_id->HTML = '<span id="address_id-container' . $rnd1 . '"></span><input type="hidden" name="address_id" id="address_id' . $rnd1 . '" value="' . html_attr($combo_address_id->SelectedData) . '">';
	$combo_address_id->MatchText = '<span id="address_id-container-readonly' . $rnd1 . '"></span><input type="hidden" name="address_id" id="address_id' . $rnd1 . '" value="' . html_attr($combo_address_id->SelectedData) . '">';
	$combo_type1->HTML = '<span id="type1-container' . $rnd1 . '"></span><input type="hidden" name="type1" id="type1' . $rnd1 . '" value="' . html_attr($combo_type1->SelectedData) . '">';
	$combo_type1->MatchText = '<span id="type1-container-readonly' . $rnd1 . '"></span><input type="hidden" name="type1" id="type1' . $rnd1 . '" value="' . html_attr($combo_type1->SelectedData) . '">';
	$combo_type2->HTML = '<span id="type2-container' . $rnd1 . '"></span><input type="hidden" name="type2" id="type2' . $rnd1 . '" value="' . html_attr($combo_type2->SelectedData) . '">';
	$combo_type2->MatchText = '<span id="type2-container-readonly' . $rnd1 . '"></span><input type="hidden" name="type2" id="type2' . $rnd1 . '" value="' . html_attr($combo_type2->SelectedData) . '">';
	$combo_type3->HTML = '<span id="type3-container' . $rnd1 . '"></span><input type="hidden" name="type3" id="type3' . $rnd1 . '" value="' . html_attr($combo_type3->SelectedData) . '">';
	$combo_type3->MatchText = '<span id="type3-container-readonly' . $rnd1 . '"></span><input type="hidden" name="type3" id="type3' . $rnd1 . '" value="' . html_attr($combo_type3->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_title__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['title'] : $filterer_title); ?>"};
		AppGini.current_address_id__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['address_id'] : $filterer_address_id); ?>"};
		AppGini.current_type1__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['type1'] : $filterer_type1); ?>"};
		AppGini.current_type2__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['type2'] : $filterer_type2); ?>"};
		AppGini.current_type3__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['type3'] : $filterer_type3); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(title_reload__RAND__) == 'function') title_reload__RAND__();
				if(typeof(address_id_reload__RAND__) == 'function') address_id_reload__RAND__();
				if(typeof(type1_reload__RAND__) == 'function') type1_reload__RAND__();
				if(typeof(type2_reload__RAND__) == 'function') type2_reload__RAND__();
				if(typeof(type3_reload__RAND__) == 'function') type3_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function title_reload__RAND__(){
			new Ajax.Updater("title-container__RAND__", "ajax_combo.php", {
				parameters: { t: "partner", f: "title", id: AppGini.current_title__RAND__.value, text: AppGini.current_title__RAND__.text, o: <?php echo (($AllowUpdate || $AllowInsert) && !$dvprint ? '1' : '0'); ?> },
				method: "get",
				encoding: "<?php echo datalist_db_encoding; ?>",
				evalScripts: true,
				onComplete: function(){ title_changed__RAND__(); }
			});
		}
		function title_changed__RAND__(){
			if($j("input[name=title]").length){
				if($j("input[name=title]:checked").length){
					AppGini.current_title__RAND__.value = $j("input[name=title]:checked").val();
					AppGini.current_title__RAND__.text = "";
				}else{
					AppGini.current_title__RAND__.value = "";
					AppGini.current_title__RAND__.text = "";
				}
			}

			if(typeof(title_update_autofills__RAND__) == 'function') title_update_autofills__RAND__();
		}
		function address_id_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#address_id-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_address_id__RAND__.value, t: 'partner', f: 'address_id' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="address_id"]').val(resp.results[0].id);
							$j('[id=address_id-container-readonly__RAND__]').html('<span id="address_id-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=address_view_parent]').hide(); }else{ $j('.btn[id=address_view_parent]').show(); }


							if(typeof(address_id_update_autofills__RAND__) == 'function') address_id_update_autofills__RAND__();
						}
					});
				},
				width: ($j('fieldset .col-xs-11').width() - select2_max_width_decrement()) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'partner', f: 'address_id' }; },
					results: function(resp, page){ return resp; }
				},
				escapeMarkup: function(str){ return str; }
			}).on('change', function(e){
				AppGini.current_address_id__RAND__.value = e.added.id;
				AppGini.current_address_id__RAND__.text = e.added.text;
				$j('[name="address_id"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=address_view_parent]').hide(); }else{ $j('.btn[id=address_view_parent]').show(); }


				if(typeof(address_id_update_autofills__RAND__) == 'function') address_id_update_autofills__RAND__();
			});

			if(!$j("#address_id-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_address_id__RAND__.value, t: 'partner', f: 'address_id' },
					success: function(resp){
						$j('[name="address_id"]').val(resp.results[0].id);
						$j('[id=address_id-container-readonly__RAND__]').html('<span id="address_id-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=address_view_parent]').hide(); }else{ $j('.btn[id=address_view_parent]').show(); }

						if(typeof(address_id_update_autofills__RAND__) == 'function') address_id_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_address_id__RAND__.value, t: 'partner', f: 'address_id' },
				success: function(resp){
					$j('[id=address_id-container__RAND__], [id=address_id-container-readonly__RAND__]').html('<span id="address_id-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=address_view_parent]').hide(); }else{ $j('.btn[id=address_view_parent]').show(); }

					if(typeof(address_id_update_autofills__RAND__) == 'function') address_id_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function type1_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#type1-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_type1__RAND__.value, t: 'partner', f: 'type1' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="type1"]').val(resp.results[0].id);
							$j('[id=type1-container-readonly__RAND__]').html('<span id="type1-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=psn_type_view_parent]').hide(); }else{ $j('.btn[id=psn_type_view_parent]').show(); }


							if(typeof(type1_update_autofills__RAND__) == 'function') type1_update_autofills__RAND__();
						}
					});
				},
				width: ($j('fieldset .col-xs-11').width() - select2_max_width_decrement()) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'partner', f: 'type1' }; },
					results: function(resp, page){ return resp; }
				},
				escapeMarkup: function(str){ return str; }
			}).on('change', function(e){
				AppGini.current_type1__RAND__.value = e.added.id;
				AppGini.current_type1__RAND__.text = e.added.text;
				$j('[name="type1"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=psn_type_view_parent]').hide(); }else{ $j('.btn[id=psn_type_view_parent]').show(); }


				if(typeof(type1_update_autofills__RAND__) == 'function') type1_update_autofills__RAND__();
			});

			if(!$j("#type1-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_type1__RAND__.value, t: 'partner', f: 'type1' },
					success: function(resp){
						$j('[name="type1"]').val(resp.results[0].id);
						$j('[id=type1-container-readonly__RAND__]').html('<span id="type1-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=psn_type_view_parent]').hide(); }else{ $j('.btn[id=psn_type_view_parent]').show(); }

						if(typeof(type1_update_autofills__RAND__) == 'function') type1_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_type1__RAND__.value, t: 'partner', f: 'type1' },
				success: function(resp){
					$j('[id=type1-container__RAND__], [id=type1-container-readonly__RAND__]').html('<span id="type1-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=psn_type_view_parent]').hide(); }else{ $j('.btn[id=psn_type_view_parent]').show(); }

					if(typeof(type1_update_autofills__RAND__) == 'function') type1_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function type2_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#type2-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_type2__RAND__.value, t: 'partner', f: 'type2' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="type2"]').val(resp.results[0].id);
							$j('[id=type2-container-readonly__RAND__]').html('<span id="type2-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=psn_type_view_parent]').hide(); }else{ $j('.btn[id=psn_type_view_parent]').show(); }


							if(typeof(type2_update_autofills__RAND__) == 'function') type2_update_autofills__RAND__();
						}
					});
				},
				width: ($j('fieldset .col-xs-11').width() - select2_max_width_decrement()) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'partner', f: 'type2' }; },
					results: function(resp, page){ return resp; }
				},
				escapeMarkup: function(str){ return str; }
			}).on('change', function(e){
				AppGini.current_type2__RAND__.value = e.added.id;
				AppGini.current_type2__RAND__.text = e.added.text;
				$j('[name="type2"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=psn_type_view_parent]').hide(); }else{ $j('.btn[id=psn_type_view_parent]').show(); }


				if(typeof(type2_update_autofills__RAND__) == 'function') type2_update_autofills__RAND__();
			});

			if(!$j("#type2-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_type2__RAND__.value, t: 'partner', f: 'type2' },
					success: function(resp){
						$j('[name="type2"]').val(resp.results[0].id);
						$j('[id=type2-container-readonly__RAND__]').html('<span id="type2-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=psn_type_view_parent]').hide(); }else{ $j('.btn[id=psn_type_view_parent]').show(); }

						if(typeof(type2_update_autofills__RAND__) == 'function') type2_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_type2__RAND__.value, t: 'partner', f: 'type2' },
				success: function(resp){
					$j('[id=type2-container__RAND__], [id=type2-container-readonly__RAND__]').html('<span id="type2-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=psn_type_view_parent]').hide(); }else{ $j('.btn[id=psn_type_view_parent]').show(); }

					if(typeof(type2_update_autofills__RAND__) == 'function') type2_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function type3_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#type3-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_type3__RAND__.value, t: 'partner', f: 'type3' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="type3"]').val(resp.results[0].id);
							$j('[id=type3-container-readonly__RAND__]').html('<span id="type3-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=psn_type_view_parent]').hide(); }else{ $j('.btn[id=psn_type_view_parent]').show(); }


							if(typeof(type3_update_autofills__RAND__) == 'function') type3_update_autofills__RAND__();
						}
					});
				},
				width: ($j('fieldset .col-xs-11').width() - select2_max_width_decrement()) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'partner', f: 'type3' }; },
					results: function(resp, page){ return resp; }
				},
				escapeMarkup: function(str){ return str; }
			}).on('change', function(e){
				AppGini.current_type3__RAND__.value = e.added.id;
				AppGini.current_type3__RAND__.text = e.added.text;
				$j('[name="type3"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=psn_type_view_parent]').hide(); }else{ $j('.btn[id=psn_type_view_parent]').show(); }


				if(typeof(type3_update_autofills__RAND__) == 'function') type3_update_autofills__RAND__();
			});

			if(!$j("#type3-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_type3__RAND__.value, t: 'partner', f: 'type3' },
					success: function(resp){
						$j('[name="type3"]').val(resp.results[0].id);
						$j('[id=type3-container-readonly__RAND__]').html('<span id="type3-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=psn_type_view_parent]').hide(); }else{ $j('.btn[id=psn_type_view_parent]').show(); }

						if(typeof(type3_update_autofills__RAND__) == 'function') type3_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_type3__RAND__.value, t: 'partner', f: 'type3' },
				success: function(resp){
					$j('[id=type3-container__RAND__], [id=type3-container-readonly__RAND__]').html('<span id="type3-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=psn_type_view_parent]').hide(); }else{ $j('.btn[id=psn_type_view_parent]').show(); }

					if(typeof(type3_update_autofills__RAND__) == 'function') type3_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/partner_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/partner_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Partner details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return partner_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return partner_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return partner_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#company_name').replaceWith('<div class=\"form-control-static\" id=\"company_name\">' + (jQuery('#company_name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#title').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#title_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#fname').replaceWith('<div class=\"form-control-static\" id=\"fname\">' + (jQuery('#fname').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#lname').replaceWith('<div class=\"form-control-static\" id=\"lname\">' + (jQuery('#lname').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#mailname').replaceWith('<div class=\"form-control-static\" id=\"mailname\">' + (jQuery('#mailname').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#email').replaceWith('<div class=\"form-control-static\" id=\"email\">' + (jQuery('#email').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#email, #email-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#phone').replaceWith('<div class=\"form-control-static\" id=\"phone\">' + (jQuery('#phone').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#mobile').replaceWith('<div class=\"form-control-static\" id=\"mobile\">' + (jQuery('#mobile').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#address_id').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#address_id_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#username').replaceWith('<div class=\"form-control-static\" id=\"username\">' + (jQuery('#username').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#password').replaceWith('<div class=\"form-control-static\" id=\"password\">' + (jQuery('#password').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#type1').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#type1_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#type2').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#type2_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#type3').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#type3_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#commission_rate').replaceWith('<div class=\"form-control-static\" id=\"commission_rate\">' + (jQuery('#commission_rate').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(title)%%>', $combo_title->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(title)%%>', $combo_title->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(title)%%>', urlencode($combo_title->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(address_id)%%>', $combo_address_id->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(address_id)%%>', $combo_address_id->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(address_id)%%>', urlencode($combo_address_id->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(type1)%%>', $combo_type1->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(type1)%%>', $combo_type1->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(type1)%%>', urlencode($combo_type1->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(type2)%%>', $combo_type2->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(type2)%%>', $combo_type2->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(type2)%%>', urlencode($combo_type2->MatchText), $templateCode);
	$templateCode=str_replace('<%%COMBO(type3)%%>', $combo_type3->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(type3)%%>', $combo_type3->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(type3)%%>', urlencode($combo_type3->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'title' => array('psn_title', 'Title'), 'address_id' => array('address', 'Address id'), 'type1' => array('psn_type', 'Type1'), 'type2' => array('psn_type', 'Type2'), 'type3' => array('psn_type', 'Type3'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(company_name)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(title)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(fname)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(lname)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(mailname)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(email)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(phone)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(mobile)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(address_id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(username)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(password)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(type1)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(type2)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(type3)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(commission_rate)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(company_name)%%>', html_attr($row['company_name']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(company_name)%%>', urlencode($urow['company_name']), $templateCode);
		$templateCode=str_replace('<%%VALUE(title)%%>', html_attr($row['title']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(title)%%>', urlencode($urow['title']), $templateCode);
		$templateCode=str_replace('<%%VALUE(fname)%%>', html_attr($row['fname']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(fname)%%>', urlencode($urow['fname']), $templateCode);
		$templateCode=str_replace('<%%VALUE(lname)%%>', html_attr($row['lname']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(lname)%%>', urlencode($urow['lname']), $templateCode);
		$templateCode=str_replace('<%%VALUE(mailname)%%>', html_attr($row['mailname']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(mailname)%%>', urlencode($urow['mailname']), $templateCode);
		if($dvprint){
			$templateCode = str_replace('<%%VALUE(email)%%>', nl2br(html_attr($row['email'])), $templateCode);
		}else{
			$templateCode = str_replace('<%%VALUE(email)%%>', html_attr($row['email']), $templateCode);
		}
		$templateCode=str_replace('<%%URLVALUE(email)%%>', urlencode($urow['email']), $templateCode);
		$templateCode=str_replace('<%%VALUE(phone)%%>', html_attr($row['phone']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(phone)%%>', urlencode($urow['phone']), $templateCode);
		$templateCode=str_replace('<%%VALUE(mobile)%%>', html_attr($row['mobile']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(mobile)%%>', urlencode($urow['mobile']), $templateCode);
		$templateCode=str_replace('<%%VALUE(address_id)%%>', html_attr($row['address_id']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(address_id)%%>', urlencode($urow['address_id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(username)%%>', html_attr($row['username']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(username)%%>', urlencode($urow['username']), $templateCode);
		$templateCode=str_replace('<%%VALUE(password)%%>', html_attr($row['password']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(password)%%>', urlencode($urow['password']), $templateCode);
		$templateCode=str_replace('<%%VALUE(type1)%%>', html_attr($row['type1']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(type1)%%>', urlencode($urow['type1']), $templateCode);
		$templateCode=str_replace('<%%VALUE(type2)%%>', html_attr($row['type2']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(type2)%%>', urlencode($urow['type2']), $templateCode);
		$templateCode=str_replace('<%%VALUE(type3)%%>', html_attr($row['type3']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(type3)%%>', urlencode($urow['type3']), $templateCode);
		$templateCode=str_replace('<%%VALUE(commission_rate)%%>', html_attr($row['commission_rate']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(commission_rate)%%>', urlencode($urow['commission_rate']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(company_name)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(company_name)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(title)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(title)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(fname)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(fname)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(lname)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(lname)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(mailname)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(mailname)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(email)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(email)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(phone)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(phone)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(mobile)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(mobile)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(address_id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(address_id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(username)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(username)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(password)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(password)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(type1)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(type1)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(type2)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(type2)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(type3)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(type3)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(commission_rate)%%>', '0.50', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(commission_rate)%%>', urlencode('0.50'), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
			$templateCode.="\n\tif(document.getElementById('emailEdit')){ document.getElementById('emailEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('emailEditLink')){ document.getElementById('emailEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('partner');
	if($selected_id){
		$jdata = get_joined_record('partner', $selected_id);
		$rdata = $row;
	}
	$cache_data = array(
		'rdata' => array_map('nl2br', array_map('addslashes', $rdata)),
		'jdata' => array_map('nl2br', array_map('addslashes', $jdata)),
	);
	$templateCode .= loadView('partner-ajax-cache', $cache_data);

	// hook: partner_dv
	if(function_exists('partner_dv')){
		$args=array();
		partner_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>