<?php
// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/trans_type.php");
	include("$currDir/trans_type_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('trans_type');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "trans_type";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`trans_type`.`id`" => "id",
		"`trans_type`.`type`" => "type",
		"IF(    CHAR_LENGTH(`acc_type1`.`type`), CONCAT_WS('',   `acc_type1`.`type`), '') /* Acc type */" => "acc_type",
		"`trans_type`.`description`" => "description"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`trans_type`.`id`',
		2 => 2,
		3 => '`acc_type1`.`type`',
		4 => 4
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`trans_type`.`id`" => "id",
		"`trans_type`.`type`" => "type",
		"IF(    CHAR_LENGTH(`acc_type1`.`type`), CONCAT_WS('',   `acc_type1`.`type`), '') /* Acc type */" => "acc_type",
		"`trans_type`.`description`" => "description"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`trans_type`.`id`" => "ID",
		"`trans_type`.`type`" => "Type",
		"IF(    CHAR_LENGTH(`acc_type1`.`type`), CONCAT_WS('',   `acc_type1`.`type`), '') /* Acc type */" => "Acc type",
		"`trans_type`.`description`" => "Description"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`trans_type`.`id`" => "id",
		"`trans_type`.`type`" => "type",
		"IF(    CHAR_LENGTH(`acc_type1`.`type`), CONCAT_WS('',   `acc_type1`.`type`), '') /* Acc type */" => "acc_type",
		"`trans_type`.`description`" => "description"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'acc_type' => 'Acc type');

	$x->QueryFrom = "`trans_type` LEFT JOIN `acc_type` as acc_type1 ON `acc_type1`.`id`=`trans_type`.`acc_type` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "trans_type_view.php";
	$x->RedirectAfterInsert = "trans_type_view.php?SelectedID=#ID#";
	$x->TableTitle = "Trans type";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`trans_type`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150);
	$x->ColCaption = array("ID", "Type", "Acc type", "Description");
	$x->ColFieldName = array('id', 'type', 'acc_type', 'description');
	$x->ColNumber  = array(1, 2, 3, 4);

	// template paths below are based on the app main directory
	$x->Template = 'templates/trans_type_templateTV.html';
	$x->SelectedTemplate = 'templates/trans_type_templateTVS.html';
	$x->TemplateDV = 'templates/trans_type_templateDV.html';
	$x->TemplateDVP = 'templates/trans_type_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `trans_type`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='trans_type' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `trans_type`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='trans_type' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`trans_type`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: trans_type_init
	$render=TRUE;
	if(function_exists('trans_type_init')){
		$args=array();
		$render=trans_type_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: trans_type_header
	$headerCode='';
	if(function_exists('trans_type_header')){
		$args=array();
		$headerCode=trans_type_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: trans_type_footer
	$footerCode='';
	if(function_exists('trans_type_footer')){
		$args=array();
		$footerCode=trans_type_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>