<?php
// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/transaction.php");
	include("$currDir/transaction_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('transaction');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "transaction";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`transaction`.`id`" => "id",
		"`transaction`.`date`" => "date",
		"`transaction`.`property_id`" => "property_id",
		"`transaction`.`type`" => "type",
		"CONCAT('&pound;', FORMAT(`transaction`.`amount`, 2))" => "amount"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`transaction`.`id`',
		2 => 2,
		3 => '`transaction`.`property_id`',
		4 => '`transaction`.`type`',
		5 => '`transaction`.`amount`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`transaction`.`id`" => "id",
		"`transaction`.`date`" => "date",
		"`transaction`.`property_id`" => "property_id",
		"`transaction`.`type`" => "type",
		"CONCAT('&pound;', FORMAT(`transaction`.`amount`, 2))" => "amount"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`transaction`.`id`" => "ID",
		"`transaction`.`date`" => "Date",
		"`transaction`.`property_id`" => "Property id",
		"`transaction`.`type`" => "Type",
		"`transaction`.`amount`" => "Amount"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`transaction`.`id`" => "id",
		"`transaction`.`date`" => "date",
		"`transaction`.`property_id`" => "property_id",
		"`transaction`.`type`" => "type",
		"CONCAT('&pound;', FORMAT(`transaction`.`amount`, 2))" => "amount"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`transaction` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "transaction_view.php";
	$x->RedirectAfterInsert = "transaction_view.php?SelectedID=#ID#";
	$x->TableTitle = "Transaction";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`transaction`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150);
	$x->ColCaption = array("ID", "Date", "Property id", "Type", "Amount");
	$x->ColFieldName = array('id', 'date', 'property_id', 'type', 'amount');
	$x->ColNumber  = array(1, 2, 3, 4, 5);

	// template paths below are based on the app main directory
	$x->Template = 'templates/transaction_templateTV.html';
	$x->SelectedTemplate = 'templates/transaction_templateTVS.html';
	$x->TemplateDV = 'templates/transaction_templateDV.html';
	$x->TemplateDVP = 'templates/transaction_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `transaction`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='transaction' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `transaction`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='transaction' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`transaction`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: transaction_init
	$render=TRUE;
	if(function_exists('transaction_init')){
		$args=array();
		$render=transaction_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: transaction_header
	$headerCode='';
	if(function_exists('transaction_header')){
		$args=array();
		$headerCode=transaction_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: transaction_footer
	$footerCode='';
	if(function_exists('transaction_footer')){
		$args=array();
		$footerCode=transaction_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>